<p>Saúl 'Canelo' Álvarez (57-2-2, 39 KO's) aparentemente decidió adherirse a su contrato con Matchroom Boxing.

El peleador mexicano dejó entrever que en septiembre completará la trilogía contra Gennadiy Golovkin (42-1-1, 37 KO's) en vez de buscar la revancha inmediata ante el ruso Dmitry Bivol (20-0-0, 11 KO's), el hombre que le derrotó el pasado 7 de mayo en Las Vegas.
La pelea frente a GGG, largamente esperada por los fanáticos, sería el 17 de septiembre en un lugar por definir, y estará matizada por circunstancias inusuales que se desprenden del inesperado revés del mexicano, situación que cortó una racha de 16 peleas invicto durante alrededor de nueve años.

Los expertos de ESPN Digital hicieron un primer análisis sobre la decisión del mexicano de no "perseguir" de inmediato a Bivol y lo que podría acontecer en uno de los duelos más esperados en el mundo del boxeo.</p>
</p>¿Perdió fuerza la trilogía tras la derrota de Canelo?
La respuesta más sencilla, y con la cual imagino mucha gente se identificará, es un 'sí'. Obvio, Canelo viene de perder, por tanto, pierde brillo. Pero no tan rápido...

La clave está en el morbo. Imagina el escenario contrario, con un Canelo victorioso sobre Bivol, aun enrachado y hasta más encumbrado, que vendría a aniquilar a Golovkin y con ello a definir, de una vez y por todas, la rivalidad más intensa de su carrera, considerando que nunca estuvo ni tan siquiera cerca de poder vengar su otro revés, ante Floyd Mayweather.

Un cuadro interesante, no cabe duda, pero muy predecible. Réstale además el factor de la edad de GGG y su debut en las 168 libras, y todavía tienes una propuesta atractiva, pero no comparable a la que se generó tras el revés de Canelo ante Bivol.

En lugar de las circunstancias descritas, el Canelo que subirá al ring en septiembre es un púgil ansioso por demostrar que sigue siendo el rey, pero a la vez vulnerable, ante su peor enemigo, que ya venía con el bagaje de considerarse vencedor de las primeras dos peleas entre ambos. Suma y resta, y en vez del resultado cuasi predecible de la primera opción, puedes tener un verdadero banquete boxístico. (Jaime Vega-Curry, ESPN Digital)</p>
